# -*- coding: utf-8 -*-
"""Calendar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z5RJ_in4_ndZ1wesLOrRnb0fVH-7uOHw
"""

list1 = [['09:00', '10:30'], ['12:00', '13:00'], ['16:00', '17:00']]
ext1 = ['9:00', '20:00']
list2 = [['10:00', '11:30'], ['12:30', '14:30'], ['14:30', '15:00'], ['16:00', '17:00']]
ext2 = ['10:00', '18:30']

def change_small(list):
  list = [ float(i.replace(':', '.')) for i in list]
  return list

def change_big(otherlist):
  otherlist = [ [float(item.replace(':', '.')) for item in otheri] for otheri in otherlist]
  return otherlist

ext = ext1 + ext2
listfull = list1 + list2

def start_end_time(lista):
  newlist = []
  lung = len(lista)
  newlist = change_small(lista)
  newlist.sort()
  lateno = newlist[lung//2]
  earlyno = newlist[lung//2 - 1]
  startfinish = [earlyno, lateno]

  return startfinish
  
def full_calendar(liste):
  otherlist = []
  fullnewlist = change_big(liste)
  fullnewlist.sort()
  return fullnewlist

def find_slots(calendar, startfinish):
  options = []
  min = max(calendar[0][1], startfinish[0])
  for item in calendar[1:]:
    if min >= item[0] and min <= item[1]:
      min = item[1]
    elif min >= item[0] and min > item[1]:
      continue
    elif min < item[0] and item[1] <= startfinish[1]:
      options.append([min,item[0]])
      min = item[1]
    else:
      break
      
  if calendar[-1][1] < startfinish[1]:
    options.append([calendar[-1][1], startfinish[1]])
  
  return options

find_slots(full_calendar(listfull), start_end_time(ext))
    


#full_calendar(listfull)
#start_end_time(ext)